server:
  port: 8004
spring:
  application:
    name: business-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8001/eureka