server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #禁止eureka将自己注册
    fetch-registry: false    #只允许eureka进行管理,不允许检索
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      配置多个eureka
        #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

#匹配单个eureka
#        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/